/* Generated by AN DISI Unibo */ 
package it.unibo.webgui

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Webgui ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
		        var CurrentState = "{}"
		
		        fun stateUpdate(json: String){
		            CurrentState = json
		            println("Hold State: $CurrentState") 
		        }
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outblack("$name | START")
						observeResource("127.0.0.1","8000","ctx_cargoservice","hold","hold_update")
						CommUtils.outblack("$name | getting hold state for the first time")
						request("get_hold_state", "get_hold_state(si)" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleHoldState",cond=whenReply("hold_state"))
				}	 
				state("handleHoldState") { //this:State
					action { //it:State
						CommUtils.outblack("$name | processing reply")
						if( checkMsgContent( Term.createTerm("hold_state(JSonString)"), Term.createTerm("hold_state(JSON)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									            val receivedState = payloadArg(0)
									            println("$name | initial hold state: $receivedState") 
									            stateUpdate(receivedState)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listening", cond=doswitch() )
				}	 
				state("listening") { //this:State
					action { //it:State
						CommUtils.outblack("$name | waiting for hold updates")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="update_webgui",cond=whenEvent("hold_update"))
					transition(edgeName="t12",targetState="update_webgui",cond=whenDispatch("hold_update"))
				}	 
				state("update_webgui") { //this:State
					action { //it:State
						CommUtils.outred("$name | update $currentMsg")
						if( checkMsgContent( Term.createTerm("hold_update(JSonString,TERM)"), Term.createTerm("hold_update(JSON)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									            var UpdateJson = payloadArg(0)
									            println("$name | hold update received: $UpdateJson") 
									            stateUpdate(UpdateJson)
									
								updateResourceRep( CurrenState  
								)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listening", cond=doswitch() )
				}	 
			}
		}
} 
