/* Generated by AN DISI Unibo */ 
package it.unibo.webgui

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Webgui ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 
		        var currentState = "{}"
		        
		        fun stateUpdate(json: String){
		            currentState = json
		            println("UPDATE RECEIVED: $json") 
		        }
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outblue("$name | start")
						CommUtils.outblue("$name | getting hold state for the first time")
						request("get_hold_state", "get_hold_state(si)" ,"hold_mock" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="update_gui",cond=whenReply("hold_state"))
				}	 
				state("update_gui") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("hold_update(JSonString)"), Term.createTerm("hold_update(JSonString)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								            	var Update = payloadArg(0)
								            	println("$name | " + Update)
								            	stateUpdate(Update)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listening", cond=doswitch() )
				}	 
				state("listening") { //this:State
					action { //it:State
						CommUtils.outblue("$name | Ready to receive hold updates")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="update_gui",cond=whenEvent("hold_update"))
				}	 
			}
		}
} 
