/* Generated by AN DISI Unibo */ 
package it.unibo.measure_processor

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.IntervalliMisurazioni

class Measure_processor ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 
				val DFREE = 30
				var CurrentIntervallo = IntervalliMisurazioni.PRIMA_MISURAZIONE
				var LastIntervallo = IntervalliMisurazioni.PRIMA_MISURAZIONE
				// conta quanti misurazioni di fila sono cadute nello stesso intervallo
				var CounterIntervallo = 1
				// flag che mi dice se sono in uno stato di malfunzionamento
				var Guasto = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("$name | start")
						subscribeToLocalActor("sonardevice") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listen_for_measurement", cond=doswitch() )
				}	 
				state("listen_for_measurement") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="process_measurement",cond=whenEvent("measurement"))
				}	 
				state("process_measurement") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("measurement(CM)"), Term.createTerm("measurement(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												val M = payloadArg(0).toInt()	
												CounterIntervallo++
								if(   M < DFREE/2  
								 ){ CurrentIntervallo = IntervalliMisurazioni.CONTAINER_PRESENTE  
								if(  Guasto  
								 ){CommUtils.outgreen("$name | sonar ripristinato")
								 Guasto = false  
								emit("riprendi_tutto", "riprendi_tutto(si)" ) 
								}
								}
								if(  M >= DFREE/2 && M <= DFREE  
								 ){ CurrentIntervallo = IntervalliMisurazioni.CONTAINER_ASSENTE  
								if(  Guasto  
								 ){CommUtils.outgreen("$name | sonar ripristinato")
								 Guasto = false  
								emit("riprendi_tutto", "riprendi_tutto(si)" ) 
								}
								}
								if(  M > DFREE  
								 ){ CurrentIntervallo = IntervalliMisurazioni.GUASTO  
								}
								
												if(CurrentIntervallo==LastIntervallo && LastIntervallo!=IntervalliMisurazioni.PRIMA_MISURAZIONE) {
								//					CommUtils.outyellow("consistenza: $CounterIntervallo") // DEBUG
													
													// switch di Kotlin
													when(CurrentIntervallo) {
													    IntervalliMisurazioni.CONTAINER_PRESENTE -> {
													        if(CounterIntervallo == 3) {
													        	CommUtils.outmagenta("Container presente consistentemente")
								emit("container_arrived", "container_arrived(si)" ) 
								
													    		CounterIntervallo = 0
													    	}
													    }
													    IntervalliMisurazioni.CONTAINER_ASSENTE -> {
													    	if(CounterIntervallo == 3) {
													        	CommUtils.outmagenta("Container assente consistentemente")
								emit("container_absent", "container_absent(si)" ) 
								
													    		CounterIntervallo = 0
													    	}
													    }
													    IntervalliMisurazioni.GUASTO -> {
													    	if(CounterIntervallo == 3) {
																CommUtils.outred("Guasto consistente")	
																Guasto = true
								emit("interrompi_tutto", "interrompi_tutto(si)" ) 
								
																CounterIntervallo = 0			    		
													    	}
													    }
													    else -> {
													    	// ci vuole se no kotlin si lamenta in quanto
													    	// i casi sopra non sono esausitivi
													    }
													}
												} 
												else {
													// 1 in quanto questa è la prima misurazione appartenente al suo intervallo
													CounterIntervallo = 1
								//					CommUtils.outyellow("consistenza: $CounterIntervallo") // DEBUG
												}
												
												LastIntervallo = CurrentIntervallo
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listen_for_measurement", cond=doswitch() )
				}	 
			}
		}
} 
